name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  coding-guidelines:
    name: Coding Guidelines

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: none, ctype, curl, date, dom, json, libxml, mbstring, openssl, phar, simplexml, soap, tokenizer, xml, xmlwriter, zlib
          coverage: none
          tools: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-ansi --no-progress

      - name: Run PHPCS
        run: composer run-script phpcs
    
  type-checker:
    name: Type Checker

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: none, ctype, curl, date, dom, json, libxml, mbstring, openssl, phar, simplexml, soap, tokenizer, xml, xmlwriter, zlib
          coverage: none
          tools: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPStan
        run: composer run-script phpstan


  unit-tests:
    name: Unit Tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: none, ctype, curl, date, dom, json, libxml, mbstring, openssl, phar, simplexml, soap, sockets, tokenizer, xml, xmlwriter, zlib
          coverage: none
          tools: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests with PHPUnit
        run: composer run-script test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
